### ISSUE TITLE
Variables with unset Cannot Be Auto-Completed

### ISSUE THREAD

**Issue by mylovesaber** [BashSupport-Pro/bashsupport-pro#184]
## Code outside function
```bash
aaa=q
echo 
```
When you type $a after `echo `, BSP will show `$aaa`
![image](https://github.com/user-attachments/assets/bd2ceba5-490d-43b8-9f9f-c4cd10c72bd8)

GOOD

---

If you do this first:
```bash
aaa=q
echo 
unset aaa
```
When you type $a after `echo `, BSP will show `$aaa`
![image](https://github.com/user-attachments/assets/6028b047-a37a-4788-9502-70290e0c6570)

GOOD

---

## Code inside function
```bash
f1(){
aaa=q
echo 
}

```
When you type $a after `echo `, BSP will show `$aaa`
![image](https://github.com/user-attachments/assets/4bf8735d-58f9-4713-b2c5-141358556fa2)

GOOD

---

If you do this first:
```bash
f1(){
aaa=q
echo 
unset aaa
}

```
When you type $a after `echo `, **BSP will NOT show `$aaa`**
![image](https://github.com/user-attachments/assets/8294de8b-48bd-4da4-8f8a-8f04f3b4e4d8)

BAD

**Comment by jansorg** [comment]
Thanks! I can confirm that this is a bug.

**Comment by jansorg** [comment]
I've fixed this for the next update, but it'll take a bit until that's available (4.3.2 was just released).

**Comment by jansorg** [comment]
4.4.0 with the fix is now available. Please let me know if the new version is not working as expected.

**Comment by mylovesaber** [comment]
Version: 4.4.0.243 seems not fixed yet.

Some spaces before "echo" is not the problem. If I define a variable and unset it before using it, then I use this variable between definition and unset line. BSP will not recognize this variable.
![image](https://github.com/user-attachments/assets/893a2fe4-ec4c-4df5-8ec5-a39ce7945350)

**Comment by jansorg** [comment]
@mylovesaber I'm sorry, you're right that this isn't fixed. I'll double-check why this particular case isn't working with the fix I made and I'll get this fixed for the next update.

**Comment by jansorg** [comment]
I've finally fixed this for the new update.
Completion outside a function is already fixed in 4.4.0, but it wasn't fixed inside a function definition.
I'll let you know when the update is available.

**Comment by jansorg** [comment]
Version 4.5.0 with the fix is now available.
Please let me know if it's still not working as expected.
Thank you for your patience!
